//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerryCheck_InDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int PassengerID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Nationality { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpire { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Period { get; set; }
        public string VoyageNumber { get; set; }
    }
}
